### ISSUE TITLE
Adding badges for Travis and Codecov?

### ISSUE THREAD

**Issue by MnO2** [andelf/rust-darts#13]
* The github account needs to be linked with Travis and Codecov.
* It would make the README looks good and encourage people to adopt it.

It looks like the following.
![Screenshot 2019-06-24 at 7 40 15 PM](https://user-images.githubusercontent.com/64175/60016186-009dc800-96b8-11e9-9105-85e068f937e6.png)

**Comment by andelf** [comment]
Good Point.

**Comment by andelf** [comment]
[![Build Status](https://travis-ci.org/andelf/rust-darts.svg?branch=master)](https://travis-ci.org/andelf/rust-darts)
[![codecov](https://codecov.io/gh/andelf/rust-darts/branch/master/graph/badge.svg)](https://codecov.io/gh/andelf/rust-darts)
[![Crates.io](https://img.shields.io/crates/v/darts.svg)](https://crates.io/crates/darts)
[![docs.rs](https://docs.rs/darts/badge.svg)](https://docs.rs/darts/)
